export const resources ={
    "en": {
      "translation": {
        "home":"Home",
        "categories":"Categories",
        "liveVideo":"Live Video",
        "myPlays":"My Players",
        "liveScheduled":"Live Scheduled",
        "aboutUs":"About Us",
        "termsAndConditions":"Terms & Conditions",
        "returnPolicy":"Return Policy",
        "collapseMenu":"Collapse Menu",
        "light":"Light",
        "dark":"Dark",
        "video":"Video",
        "myOrder":"My Order",
        "voucher":"Voucher",
        "delivery":"Delivery",
        "myVideo":"My Video",
        "settings":"Settings",
        "helpCenter":"Help Center",
        "answerHere":"AnswerHere",
        "favourites":"Favourites",
        "companyProfile":"Company Profile",
        "settings":"Settings",
        "languages":"Language",
        "notification":"Notification",
        "theme":"Theme",
        "supports":"Support",
      }
    },
    "bd": {
      "translation": {
        "home":"হোম",
        "categories":"ক্যাটাগরী",
        "liveVideo":"লাইভ ভিডিও",
        "myPlays":"মাই প্লে",
        "liveScheduled":"লাইভ সিডিউল",
        "aboutUs":"এবাউট আস",
        "termsAndConditions":"টার্মস এন্ড কন্ডিশন",
        "returnPolicy":"রিটার্ন পলিসি",
        "collapseMenu":"কলাপ্স",
        "light":"লাইট",
        "dark":"ডার্ক",
        "video":"ভিডিও",
        "myOrder":"মাই অর্ডার",
        "voucher":"ভাউচার",
        "delivery":"ডেলিভারি",
        "myVideo":"মাই ভিডিও",
        "settings":"সেটিংস",
        "helpCenter":"হেল্প সেন্টার",
        "answerHere":"উত্তরসমূহ",
        "favourites":"প্রিয় প্রোডাক্টস",
        "companyProfile":"কোম্পানি প্রোফইল",
        "settings":"সেটিংস",
        "languages":"ভাষা",
        "notification":"নোটিফিকেশন",
        "theme":"থিম",
        "supports":"সাপোর্ট",
      }
    }
}