export const resources ={
    "en": {
      "translation": {
        "home":"Home",
        "categories":"Categories",
        "liveVideo":"Live Video",
        "myPlays":"My Players",
        "liveScheduled":"Live Scheduled",
        "aboutUs":"About Us",
        "termsAndConditions":"Terms & Conditions",
        "returnPolicy":"Return Policy",
        "returnPolicyDetails":"The Return and Refund Policy of Beautysiaa is designed to provide customers with a hassle-free return and refund experience. At Beautysiaa, we want all of our customers to be completely satisfied with their purchases. However, we understand that there may be occasions when a customer is not satisfied with their purchase and would like to return the product for a refund. If you are not satisfied with your purchase, you can return the product to us within 30 days of the purchase date. All returned products must be in their original packaging and in the same condition as when they were received.Once we receive the returned product, we will process the refund within 7-10 business days. The refund will be issued to the original method of payment.Please note that original shipping charges are non-refundable. In the event of a refund, the customer will be responsible for covering the cost of return shipping.If you have any questions about our Return and Refund Policy, please don’t hesitate to contact us at info@beautysiaa.com. We will be happy to assist you.",
        "collapseMenu":"Collapse Menu",
        "light":"Light",
        "dark":"Dark",
        "video":"Video",
        "myOrder":"My Order",
        "voucher":"Voucher",
        "delivery":"Delivery",
        "myVideo":"My Video",
        "settings":"Settings",
        "helpCenter":"Help Center",
        "answerHere":"AnswerHere",
        "favourites":"Favourites",
        "companyProfile":"Company Profile",
        "settings":"Settings",
        "languages":"Language",
        "notification":"Notification",
        "theme":"Theme",
        "supports":"Support",
        "phoneLogin":"Sign Up With A Phone Number",
        "enterPhone":"Enter phone number",
        "generateCode":"Generate Code",
        "or":"OR",
        "googleLogin":"CONTINUE WITH GOOGLE",
        "facebookLogin":"CONTINUE WITH FACEBOOK",
        "guestLogin":"Guest Login",
        "codeSent":"Code was send your number",
        "expireOn":"This code will expire on 5 minutes",
        "verifyCode":"VERIFY CODE",
        "resentCode":"RESEND CODE",
        "enterShipping":"ENTER SHIPPING DETAILS",
        "firstName":"First name",
        "lastName":"Last name",
        "emailAddress":"Email address",
        "phoneNumber":"Phone Number",
        "address":"Address",
        "postCode":"Post code",
        "continueCheckout":"Continue Checkout",
        "changeAddress":"Change Address",
        "paymentMethod":"Select payment method",
        "showAll":"Show All",
        "cod":"Cash on Delivery (COD)",
        "bkash":"Bkash/Nagad/Rocket",
        "card":"Card Method",
        "subTotal":"Subtotal",
        "deliveryCharges":"Delivery Charges",
        "valueAndTaxes":"Value & Taxes",
        "totalAmounts":"Total Amounts",
        "orderConfirmed":"Order Confirmed",
        "checkout":"Checkout",
        "continueShopping":"Continue Shopping",
        "success":"Success",
        "thanksMessage":"Thank you for purchasing. Your order will be shipped 2-4 working days",
        "searchProducts":"Search products",
        "productFilter":"Products filter",
        "priceRange":"Price range",
        "freeShipping":"Free shipping",
        "flashSale":"Flash sale",
        "discountedProducts":"Discounted products",
        "close":"Close",
        "comboOffer":"Combo Offer",
        "searchCategories":"Search categories",
        "editProfile":"Edit Profile",
        "profile":"Profile",
        "offer":"Offer",
        "seeMore":"See more",
        "shopByCategory":"Shop by category",
        "shopBySkinConcern":"Shop by Skin Concern",
        "populaBrands":"Popular Brands",
        "cart":'Cart',
        "proceedToCheckout":'Place Order',
        "signIn":"Signin",
        "signInNow":"Signin Now",
        "enteraVoucherCode":'Enter Voucher Code ...',
        "apply":'Apply',
        "cycloneOffer":'Cyclone Offer',
        "appVersion":'App version',
        "getCouponMsg":'Enter',
        "getCouponMsgTwo":'to get this coupon',
        "off":'OFF',
        "on":'ON',
        "accountDeletionAlert":'Do you want to delete this account? It will delete your account informations also!',
        "deleteNow":'Delete now',
        "cancel":'Cancel',
        "logout":'Logout',

      }
    },
    "bd": {
      "translation": {
        "home":"হোম",
        "categories":"ক্যাটাগরী",
        "liveVideo":"লাইভ ভিডিও",
        "myPlays":"মাই প্লে",
        "liveScheduled":"লাইভ সিডিউল",
        "aboutUs":"এবাউট আস",
        "termsAndConditions":"টার্মস এন্ড কন্ডিশন",
        "returnPolicy":"রিটার্ন পলিসি",
        "collapseMenu":"কলাপ্স",
        "light":"লাইট",
        "dark":"ডার্ক",
        "video":"ভিডিও",
        "myOrder":"মাই অর্ডার",
        "voucher":"ভাউচার",
        "delivery":"ডেলিভারি",
        "myVideo":"মাই ভিডিও",
        "settings":"সেটিংস",
        "helpCenter":"হেল্প সেন্টার",
        "answerHere":"উত্তরসমূহ",
        "favourites":"প্রিয় প্রোডাক্টস",
        "companyProfile":"কোম্পানি প্রোফইল",
        "settings":"সেটিংস",
        "languages":"ভাষা",
        "notification":"নোটিফিকেশন",
        "theme":"থিম",
        "supports":"সাপোর্ট",
        "phoneLogin":"ফোন লগিন করুন",
        "enterPhone":"ফোন নাম্বার লিখুন",
        "generateCode":"কোড জেনারেট করুন",
        "or":"অথবা",
        "googleLogin":"গুগল লগিন করুন",
        "facebookLogin":"ফেইসবুক লগিন করুন",
        "guestLogin":"গেস্ট লগিন করুন",
        "codeSent":"আপনার ফোনে otp পাঠানো হয়েছে",
        "expireOn":"৫ মিনিটে কোড এক্সপায়ার হয়ে যাবে",
        "verifyCode":"ভেরিফাই করুন",
        "resentCode":"আবার কোড পাঠান",
        "enterShipping":"শপিং ডিটেইলস লিখুন",
        "firstName":"মূল নাম",
        "lastName":"ডাক নাম",
        "emailAddress":"ইমেইল",
        "phoneNumber":"ফোন নাম্বার",
        "address":"এড্রেস",
        "postCode":"পোস্ট কোড",
        "continueCheckout":"চেকআউট সম্পন্ন করুন",
        "changeAddress":"ঠিকানা বদলান",
        "paymentMethod":"পেমেন্ট মেথড",
        "showAll":"সব দেখুন",
        "cod":"ক্যাশ অন ডেলিভারি",
        "bkash":"বিকাশ/নগদ/রকেট",
        "card":"কার্ড মেথড",
        "subTotal":"সর্বোমোট",
        "deliveryCharges":"ডেলিভারি চার্জ",
        "valueAndTaxes":"টেক্স",
        "totalAmounts":"মোট মূল্য",
        "orderConfirmed":"অর্ডার কনফার্ম করুন",
        "checkout":"চেকআউট",
        "success":"সাকসেস",
        "continueShopping":"শপিং চালিয়ে যান",
        "thanksMessage":"কেনার জন্য আপনাকে ধন্যবাদ. আপনার অর্ডার 2-4 কার্যদিবসে পাঠানো হবে",
        "searchProducts":"প্রোডাক্ট সার্চ",
        "productFilter":"প্রোডাক্ট ফিল্টার",
        "priceRange":"প্রাইস রেন্জ",
        "freeShipping":"ফ্রি শিপিং",
        "flashSale":"ফ্লেস সেল",
        "discountedProducts":"ডিসকাউন্ট প্রোডাক্ট",
        "close":"বন্ধ করুন",
        "comboOffer":"কম্বো অফার",
        "searchCategories":"ক্যাটাগরি সার্চ",
        "editProfile":"প্রোফাইল এডিট",
        "profile":"প্রোফাইল",
        "returnPolicyDetails":"বিউটিশিয়ার রিটার্ন এবং রিফান্ড পলিসি গ্রাহকদের ঝামেলামুক্ত রিটার্ন এবং রিফান্ডের অভিজ্ঞতা প্রদানের জন্য ডিজাইন করা হয়েছে। বিউটিশিয়াতে, আমরা চাই আমাদের সমস্ত গ্রাহকরা তাদের কেনাকাটায় সম্পূর্ণরূপে সন্তুষ্ট হন। যাইহোক, আমরা বুঝি যে এমন কিছু সময় থাকতে পারে যখন একজন গ্রাহক তাদের কেনাকাটায় সন্তুষ্ট হন না এবং পণ্যটি ফেরত দিতে চান। আপনি যদি আপনার ক্রয়ের সাথে সন্তুষ্ট না হন তবে আপনি ক্রয়ের তারিখের 30 দিনের মধ্যে পণ্যটি আমাদের কাছে ফেরত দিতে পারেন। সমস্ত প্রত্যাবর্তিত পণ্য অবশ্যই তাদের আসল প্যাকেজিংয়ে থাকতে হবে এবং সেগুলি যখন প্রাপ্ত হয়েছিল সেই অবস্থায় থাকতে হবে৷ একবার আমরা ফেরত পণ্যটি পেয়ে গেলে, আমরা 7-10 কার্যদিবসের মধ্যে ফেরত প্রক্রিয়া করব৷ অর্থপ্রদানের মূল পদ্ধতিতে ফেরত দেওয়া হবে৷ অনুগ্রহ করে মনে রাখবেন যে মূল শিপিং চার্জগুলি ফেরতযোগ্য নয়৷ রিফান্ডের ক্ষেত্রে, গ্রাহক রিটার্ন শিপিংয়ের খরচ কভার করার জন্য দায়ী থাকবে। আমাদের রিটার্ন এবং রিফান্ড নীতি সম্পর্কে আপনার কোন প্রশ্ন থাকলে, info@beautysiaa.com এ আমাদের সাথে যোগাযোগ করতে দ্বিধা করবেন না। আমরা আপনাকে সাহায্য করতে খুশি হবে.",
        "offer":"অফার",
        "seeMore":"আরও দেখুন",
        "shopByCategory":"ক্যাটাগরিসমূহ",
        "shopBySkinConcern":"ত্বকের পরিচর্যায় প্রসাধনি সমূহ",
        "populaBrands":"পপুলার ব্রান্ডস",
        "cart":'কার্ট',
        "proceedToCheckout":'চেকআউট করুন',
        "signIn":"সাইন ইন",
        "signInNow":"এখুনি সাইন ইন করুন",
        "enteraVoucherCode":'কুপন কোড বসান...',
        "apply":'প্রয়োগ করুন',
        "cycloneOffer":'সাইক্লোন অফার',
        "appVersion":'ভার্সান',
        "getCouponMsg":'ডিসকাউন্ট পেতে',
        "getCouponMsgTwo":'কুপন কোডটি ব্যবহার করুন',
        "off":'অফ',
        "on":'অন',
        "accountDeletionAlert":'আপনিকি একাউন্ট ডিলেট করতে চান? একাউন্ট ডিলেটের মাধ্যমে সকল প্রকার ডাটা ডিলেট হয়ে যাবে।',
        "deleteNow":'ডিলেট করুন',
        "cancel":'বাতিল করুন',
        "logout":'লগআউট',
      }
    }
}